/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my;

public class App {
    public String getGreeting() {
        return "Hello Java " + System.getProperty("java.version");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
